apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecloud

resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - statefulset.yaml

labels:
  - pairs:
      app: tdengine
    includeSelectors: true
