apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecloud

resources:
  - tdengine_namespace.yaml
  - tdengine_configmap.yaml
  - tdengine_hostpath.yaml

labels:
  - pairs:
      app: tdengine
    includeSelectors: true
